name: amadeusapi
description: Dart package encapsulating the Amadeus Travel API
version: 0.0.1
homepage:

environment:
  sdk: '^3.1.0'
  
dependencies:
  intl: 0.18.1
  http: 1.1.0
 
dev_dependencies:
  test: 1.24.9